//imports
var http = require('http');
var SHA224 = require('sha224');
var multer = require('multer');
var express = require('express');
var app = express();
var fetchVersionInfoRouter = require('./fetchVersionInfo.route');
var indexRouter = require('./index.route');
var loginRouter = require('./login.route');
var fetchAllSubjectsRouter = require('./fetchAllSubjects.route');
var addSubjectRouter = require('./addSubject.route');
var deleteSubjectRouter = require('./deleteSubject.route');
var fetchAllTeachersRouter = require('./fetchAllTeachers.route');
var addTeacherRouter = require('./addTeacher.route');
var deleteTeacherRouter = require('./deleteTeacher.route');
var fetchAllStudentsRouter = require('./fetchAllStudents.route');
var addStudentRouter = require('./addStudent.route');
var deleteStudentRouter = require('./deleteStudent.route');
var assignSubjectToTeacherRouter = require('./assignSubjectToTeacher.route');
var fetchSubjectsAssignedToTeacherRouter = require('./fetchSubjectsAssignedToTeacher.route');
var deleteSubjectAssignedToTeacherRouter = require('./deleteSubjectAssignedToTeacher.route');
var assignSubjectToStudentRouter = require('./assignSubjectToStudent.route');
var fetchSubjectsAssignedToStudentRouter = require('./fetchSubjectsAssignedToStudent.route');
var deleteSubjectAssignedToStudentRouter = require('./deleteSubjectAssignedToStudent.route');
var assignSubjectToClassRouter = require('./assignSubjectToClass.route');
var fetchClassSubjectsRouter = require('./fetchClassSubjects.route');
var deleteSubjectAssignedToClassRouter = require('./deleteSubjectAssignedToClass.route');
var deleteExamRouter = require('./deleteExam.route');
var fetchExamsRouter = require('./fetchExams.route');
var addExamRouter = require('./addExam.route');
var fetchExamSubjectsForTeacherRouter = require('./fetchExamSubjectsForTeacher.route');
var fetchStudentsForSubjectRouter = require('./fetchStudentsForSubject.route');
var fetchSubjectsForStudentRouter = require('./fetchSubjectsForStudent.route');
var upgradeMarksForStudentRouter = require('./upgradeMarksForStudent.route');
var upgradeValuesForStudentRouter = require('./upgradeValuesForStudent.route');
var fetchAllStudentsForExamRouter = require('./fetchAllStudentsForExam.route');
var declareExamsRouter = require('./declareExams.route');
var generatePDFSingleStudentRouter = require('./generatePDFSingleStudent.route');
var fetchReportPDFRouter = require('./fetchReportPDF.route');
var fetchPDFPresentRouter = require('./fetchPDFPresent.route');
var addNoticeRouter = require('./addNotice.route');
var fetchNoticeForTeachersRouter = require('./fetchNoticeForTeachers.route');
var fetchSentNoticeForTeachersRouter = require('./fetchSentNoticeForTeachers.route');
var fetchNoticeForStudentsRouter = require('./fetchNoticeForStudents.route');
var fetchAllNotificationsRouter = require('./fetchAllNotifications.route');
var fetchAllStudentsForSubjectTeacherRouter = require('./fetchAllStudentsForSubjectTeacher.route');
var deleteClassTeacherRouter = require('./deleteClassTeacher.route');
var addClassTeacherRouter = require('./addClassTeacher.route');
var fetchClassTeacherRouter = require('./fetchClassTeacher.route');
var fetchClassStudentsRouter = require('./fetchClassStudents.route');
var fetchValuesForStudentRouter = require('./fetchValuesForStudent.route');
var generatePDFSingleStudentFullRouter = require('./generatePDFSingleStudentFull.route');
var getPasswordSMSRouter = require('./getPasswordSMS.route');
var fetchSingleStudentCompleteDetailRouter = require('./fetchSingleStudentCompleteDetail.route');
var fetchSingleStudentPersonalDetailRouter = require('./fetchSingleStudentPersonalDetail.route');
var fetchSingleStudentHouseDetailRouter = require('./fetchSingleStudentHouseDetail.route');
var editStudentLoginRouter = require('./editStudentLogin.route');
var fetchAllHostelRouter = require('./fetchAllHostels.route');
var addHostelRouter = require('./addHostel.route');
var deleteHostelRouter = require('./deleteHostel.route');
var fetchAllHouseRouter = require('./fetchAllHouse.route');
var addHouseRouter = require('./addHouse.route');
var deleteHouseRouter = require('./deleteHouse.route');

const bodyParser = require('body-parser');
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: true }));
app.use('', indexRouter);
app.use('/login', loginRouter);
app.use('/fetchVersionInfo', fetchVersionInfoRouter);
app.use('/fetchAllSubjects', fetchAllSubjectsRouter);
app.use('/addSubjects', addSubjectRouter);
app.use('/deleteSubjects', deleteSubjectRouter);
app.use('/fetchAllTeachers', fetchAllTeachersRouter);
app.use('/addTeachers', addTeacherRouter);
app.use('/deleteTeachers', deleteTeacherRouter);
app.use('/fetchAllStudents', fetchAllStudentsRouter);
app.use('/addStudents', addStudentRouter);
app.use('/deleteStudents', deleteStudentRouter);
app.use('/assignSubjectToTeacher', assignSubjectToTeacherRouter);
app.use('/fetchSubjectsAssignedToTeacher', fetchSubjectsAssignedToTeacherRouter);
app.use('/deleteSubjectAssignedToTeacher', deleteSubjectAssignedToTeacherRouter);
app.use('/assignSubjectToStudent', assignSubjectToStudentRouter);
app.use('/fetchSubjectsAssignedToStudent', fetchSubjectsAssignedToStudentRouter);
app.use('/deleteSubjectAssignedToStudent', deleteSubjectAssignedToStudentRouter);
app.use('/assignSubjectToClass', assignSubjectToClassRouter);
app.use('/fetchClassSubjects', fetchClassSubjectsRouter);
app.use('/deleteSubjectAssignedToClass', deleteSubjectAssignedToClassRouter);
app.use('/addExams', addExamRouter);
app.use('/deleteExams', deleteExamRouter);
app.use('/fetchAllExams', fetchExamsRouter);
app.use('/declareExams', declareExamsRouter);
app.use('/fetchExamSubjectsForTeacher', fetchExamSubjectsForTeacherRouter);
app.use('/fetchStudentsForSubject', fetchStudentsForSubjectRouter);
app.use('/upgradeMarksForStudent', upgradeMarksForStudentRouter);
app.use('/upgradeValuesForStudent', upgradeValuesForStudentRouter);
app.use('/fetchSubjectsForStudent', fetchSubjectsForStudentRouter);
app.use('/fetchAllStudentsForExam', fetchAllStudentsForExamRouter);
app.use('/generatePDFSingleStudent', generatePDFSingleStudentRouter);
app.use('/fetchReportPDF', fetchReportPDFRouter);
app.use('/fetchPDFPresent', fetchPDFPresentRouter);
app.use('/addNotice', addNoticeRouter);
app.use('/fetchReceivedTeacherNotifications', fetchNoticeForTeachersRouter);
app.use('/fetchSentTeacherNotifications', fetchSentNoticeForTeachersRouter);
app.use('/fetchReceivedStudentNotifications', fetchNoticeForStudentsRouter);
app.use('/fetchAllNotifications', fetchAllNotificationsRouter);
app.use('/fetchAllStudentsForSubjectTeacher', fetchAllStudentsForSubjectTeacherRouter);
app.use('/deleteClassTeacher', deleteClassTeacherRouter);
app.use('/addClassTeacher', addClassTeacherRouter);
app.use('/fetchClassTeacher', fetchClassTeacherRouter);
app.use('/fetchClassStudents', fetchClassStudentsRouter);
app.use('/fetchValuesForStudent', fetchValuesForStudentRouter);
app.use('/generatePDFSingleStudentFull', generatePDFSingleStudentFullRouter);
app.use('/getPasswordSMS', getPasswordSMSRouter);
app.use('/fetchSingleStudentCompleteDetail', fetchSingleStudentCompleteDetailRouter);
app.use('/fetchSingleStudentPersonalDetail', fetchSingleStudentPersonalDetailRouter);
app.use('/fetchSingleStudentHouseDetail', fetchSingleStudentHouseDetailRouter);
app.use('/editStudentLogin', editStudentLoginRouter);
app.use('/fetchAllHostels', fetchAllHostelRouter);
app.use('/addHostel', addHostelRouter);
app.use('/deleteHostel', deleteHostelRouter);
app.use('/fetchAllHouse', fetchAllHouseRouter);
app.use('/addHouse', addHouseRouter);
app.use('/deleteHouse', deleteHouseRouter);

const server = http.createServer(app);
server.listen(8002, ()=>{
  console.log('Server started!');
});

module.exports=app;
