# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-03 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLogin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=20, unique=True)),
                ('password', models.TextField()),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'admin_login',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExamGroupDetail',
            fields=[
                ('exam_group_id', models.AutoField(primary_key=True, serialize=False)),
                ('exam_group_name', models.CharField(max_length=100)),
                ('exam_group_date', models.CharField(max_length=30)),
                ('exam_group_type', models.CharField(max_length=20)),
                ('session', models.CharField(blank=True, max_length=20, null=True)),
                ('results_declared', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'exam_group_detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExamGroupReportsSingle',
            fields=[
                ('exam_group_id', models.IntegerField(primary_key=True, serialize=False)),
                ('student_id', models.IntegerField()),
                ('report_loc', models.CharField(max_length=200)),
                ('remote_link', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'exam_group_reports_single',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExamGroupScoring',
            fields=[
                ('exam_group_id', models.IntegerField(primary_key=True, serialize=False)),
                ('subject_id', models.IntegerField()),
                ('student_id', models.IntegerField()),
                ('max_score', models.IntegerField(blank=True, null=True)),
                ('cur_score', models.IntegerField(blank=True, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('grade', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'db_table': 'exam_group_scoring',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NotificationDetail',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('notification_creator', models.CharField(max_length=15)),
                ('creator_id', models.IntegerField(blank=True, null=True)),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.CharField(blank=True, max_length=450, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notification_detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NotificationTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_id', models.IntegerField()),
                ('target_type', models.CharField(max_length=20)),
                ('target_id', models.IntegerField(blank=True, null=True)),
                ('target_class', models.CharField(blank=True, max_length=5, null=True)),
                ('target_section', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'notification_target',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentAcademicEnrollmentDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(unique=True)),
                ('class_field', models.CharField(db_column='class', max_length=2)),
                ('section', models.CharField(max_length=1)),
                ('roll_number', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'student_academic_enrollment_detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentLogin',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=50, unique=True)),
                ('emailid', models.CharField(max_length=100, unique=True)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('unencrypted', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'student_login',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentSubjectDetail',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('subject_id', models.IntegerField()),
            ],
            options={
                'db_table': 'student_subject_detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubjectDetails',
            fields=[
                ('subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=30, unique=True)),
                ('subject_code', models.CharField(max_length=10, unique=True)),
                ('is_major', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'subject_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TeacherLogin',
            fields=[
                ('teacher_id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=50, unique=True)),
                ('emailid', models.CharField(max_length=100, unique=True)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('unencrypted', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'teacher_login',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TeacherSubjectDetail',
            fields=[
                ('teacher_id', models.IntegerField(blank=True, null=True)),
                ('subject_id', models.IntegerField(primary_key=True, serialize=False)),
                ('class_field', models.CharField(db_column='class', max_length=5)),
                ('section', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'teacher_subject_detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UpdateTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'update_tracker',
                'managed': False,
            },
        ),
    ]
