# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-27 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvaschool', '0002_authgroup_authgrouppermissions_authpermission_authuser_authusergroups_authuseruserpermissions_classt'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalenderEventDetail',
            fields=[
                ('holiday_id', models.AutoField(primary_key=True, serialize=False)),
                ('session', models.CharField(blank=True, max_length=20, null=True)),
                ('occasion', models.CharField(blank=True, max_length=50, null=True)),
                ('details', models.CharField(blank=True, max_length=500, null=True)),
                ('start_date', models.CharField(blank=True, max_length=20, null=True)),
                ('end_date', models.CharField(blank=True, max_length=20, null=True)),
                ('start_dt', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'calender_event_detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HostelDetail',
            fields=[
                ('hostel_id', models.AutoField(primary_key=True, serialize=False)),
                ('hostel_name', models.CharField(blank=True, max_length=100, null=True)),
                ('hostel_address', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'hostel_detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HouseDetail',
            fields=[
                ('house_id', models.AutoField(primary_key=True, serialize=False)),
                ('house_name', models.CharField(blank=True, max_length=30, null=True)),
                ('house_code', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'house_detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentHouseDetail',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('house_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'student_house_detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentResidentialDetail',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_of_birth', models.CharField(blank=True, max_length=20, null=True)),
                ('hostel_resident', models.CharField(blank=True, max_length=3, null=True)),
                ('residential_address', models.CharField(blank=True, max_length=100, null=True)),
                ('hostel_id', models.IntegerField(blank=True, null=True)),
                ('transportation', models.CharField(blank=True, max_length=3, null=True)),
                ('fdb_db', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'db_table': 'student_residential_detail',
                'managed': False,
            },
        ),
    ]
